/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Todos;
import jooq.tables.records.TodosRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TodosRecord> TODOS__SYNTHETIC_PK_TODOS = Internal.createUniqueKey(Todos.TODOS, DSL.name("SYNTHETIC_PK_todos"), new TableField[] { Todos.TODOS.ID }, true);
}
