/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Todos;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>todos</code>.
     */
    public static final Todos TODOS = Todos.TODOS;
}
