/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Todos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private String date;
    private Integer priority;

    public Todos() {}

    public Todos(Todos value) {
        this.id = value.id;
        this.title = value.title;
        this.date = value.date;
        this.priority = value.priority;
    }

    public Todos(
        Integer id,
        String title,
        String date,
        Integer priority
    ) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.priority = priority;
    }

    /**
     * Getter for <code>todos.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>todos.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>todos.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>todos.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>todos.date</code>.
     */
    public String getDate() {
        return this.date;
    }

    /**
     * Setter for <code>todos.date</code>.
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for <code>todos.priority</code>.
     */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Setter for <code>todos.priority</code>.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Todos other = (Todos) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        if (this.priority == null) {
            if (other.priority != null)
                return false;
        }
        else if (!this.priority.equals(other.priority))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        result = prime * result + ((this.priority == null) ? 0 : this.priority.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Todos (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(date);
        sb.append(", ").append(priority);

        sb.append(")");
        return sb.toString();
    }
}
