/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Todos;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodosRecord extends UpdatableRecordImpl<TodosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>todos.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>todos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>todos.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>todos.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>todos.date</code>.
     */
    public void setDate(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>todos.date</code>.
     */
    public String getDate() {
        return (String) get(2);
    }

    /**
     * Setter for <code>todos.priority</code>.
     */
    public void setPriority(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>todos.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodosRecord
     */
    public TodosRecord() {
        super(Todos.TODOS);
    }

    /**
     * Create a detached, initialised TodosRecord
     */
    public TodosRecord(Integer id, String title, String date, Integer priority) {
        super(Todos.TODOS);

        setId(id);
        setTitle(title);
        setDate(date);
        setPriority(priority);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TodosRecord
     */
    public TodosRecord(jooq.tables.pojos.Todos value) {
        super(Todos.TODOS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setDate(value.getDate());
            setPriority(value.getPriority());
            resetTouchedOnNotNull();
        }
    }
}
